### ISSUE TITLE
join not working?

### ISSUE THREAD

**Issue by alex0ptr** [jmespath/jp#16]
No matter what I do, I simply can't get `join` to work:
```
➜   echo '["a", "b"]' | jp 'join(", ",@)'
Error evaluating JMESPath expression: Invalid type for: <nil>, expected: []jmespath.jpType{"string"}
```
```
➜   echo '["a", "b"]' | jp 'join(`, `,@)'
Error evaluating JMESPath expression: invalid character ',' looking for beginning of value
```

**Comment by wryun** [comment]
Your syntax is wrong. Use either single quotes for literal strings, or backquotes to introduce JSON (then double quotes inside).

Double quotes are used to select named JSON elements (i.e. in the first one you're trying to select the element ", " out of your input, which doesn't exist, so you can't join on it (nil). In the second, you're trying to parse invalid JSON.
