### ISSUE TITLE
brew install command pulls another jp

### ISSUE THREAD

**Issue by obormot** [jmespath/jp#17]
README suggests the following to install from Homebrew:
```
brew tap jmespath/jmespath
brew install jp
```

This however installs another jp package
```
$ brew info jp
jp: stable 1.1.12 (bottled)
Dead simple terminal plots from JSON data
https://github.com/sgreben/jp
...
```

I believe the correct command should be
```
brew install jmespath/jmespath/jp
```

**Comment by obormot** [comment]
```
$ brew install jmespath/jmespath/jp
==> Installing jp from jmespath/jmespath
==> Downloading https://github.com/jmespath/jp/releases/download/0.1.3/jp-0.1.3.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/40455851/a6033f2c-979c-11e7-9e23-7670faf4e7be?X-Amz-Algorithm
######################################################################## 100.0%
🍺  /usr/local/Cellar/jp/0.1.3: 3 files, 3.5MB, built in 6 seconds
```

**Comment by pmareke** [comment]
Thanks so much @obormot, it works perfect for me. I was giving the following error with the "other" jp command :

`line.go:44: no valid y values given`

**Comment by mbsquid** [comment]
Ditto that thank you - was just starting to investigate this error and this answer was easy to find.

**Comment by austintraver** [comment]
This happened to me today, @obormot's solution fixed my problem, which was the same one that @pmareke was having.

**Comment by asimjalis** [comment]
Worked for me as well. README should be updated.

Here is the command that worked for me.

`brew install jmespath/jmespath/jp`

**Comment by wilsonmar** [comment]
So what is the solution? What causes "line.go:44: no valid y values given" and what will make it work?
Are you saying upgrade to jp v0.1.3?

**Comment by jamesls** [comment]
https://github.com/jmespath/jp/pull/18 is now merged with updated installation instructions.
