### ISSUE TITLE
Require binary for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [jmespath/jp#27]
I was trying to build the **Azure/azure-cli** image on arm64 platform but it requires a jp binary which is not available for the arm64 platform.
I have built the binary successfully by following below steps:

- Installed the golang 1.13 version.

- Cloned the package and cd to jp directory.

- Ran command **go build**

Do you have any plans to release binary for arm64?

It will be very helpful if the binary is released for arm64.

**Comment by odidev** [comment]
I have raised a [PR](https://github.com/jmespath/jp/pull/28). Could you please review this PR.

**Comment by jamesls** [comment]
PR is merged and the new release 0.2.0 includes this build.  Thanks!
