### ISSUE TITLE
Scientific notation for large numbers

### ISSUE THREAD

**Issue by vielmetti** [jmespath/jp#3]
The example command line is

```
curl -s 'http://microapi.theride.org/Location' | jp '[0].Id'
```

which produces this output on a recent run:

```
4.7268765e+07
```

in scientific notation, instead of simply 47268765 like I would have expected.

**Comment by jamesls** [comment]
I agree that it shouldn't print the number in scientific notation, that was definitely unintentional.  I think this is just how go's json encoder marshals the data.  I'll get this fixed.

**Comment by flisky** [comment]
The patch has introduced an regression bug. Please take a look at PR #6.

**Comment by jamesls** [comment]
Reopening as per https://github.com/jmespath/jp/pull/6

**Comment by jamesls** [comment]
Closing old issue, looks like this is fixed now with later versions of go.

```
$ echo '{"foo": 47268765}' | jp foo
47268765
```
