### ISSUE TITLE
homebrew tap uses deprecated option

### ISSUE THREAD

**Issue by dwt** [jmespath/jp#35]
After installing it via homebrew, every time I use it it shows this error message:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the jmespath/jmespath tap (not Homebrew/brew or Homebrew/core):
  /path/to/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb:8
```

**Comment by Moskovych** [comment]
Look like nobody cares about it: https://github.com/jmespath/homebrew-jmespath/issues/2

**Comment by dwt** [comment]
@jamesls ping? Are you still working on this project?

**Comment by dwt** [comment]
@jamesls ping again? Long holidays might be a thing, but are you still around?

**Comment by jamesls** [comment]
Fixed via https://github.com/jmespath/homebrew-jmespath/pull/1
