### ISSUE TITLE
will not install with homebrew

### ISSUE THREAD

**Issue by lmeadors** [jmespath/jp#36]
Title kinda says it all:

```
-> % brew install jmespath/jmespath/jp
Error: jmespath/jmespath/jp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the jmespath/jmespath tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb:8
```

I tried removing the line in question, but got a different error saying `Error: Your Command Line Tools are too outdated.` - I upgraded those and tried again and it installed.

**Comment by luhn** [comment]
I was able to install from https://github.com/jmespath/homebrew-jmespath/pull/1

```bash
brew install adrianmace/jmespath/jp
```

(This is installing from an untrusted third-party tap, use at your own risk.)

**Comment by allenrobel** [comment]
Same here, on MacOS Monterey (Intel) and brew 3.4.4.

```
(py310) foo@bar %  brew --version
Homebrew 3.4.4
Homebrew/homebrew-core (git revision 1a87949d8b9; last commit 2022-03-29)
Homebrew/homebrew-cask (git revision 47c00e64a8; last commit 2022-03-30)
(py310) foo@bar %  uname -a
Darwin AROBEL-M-15ZV 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
(py310) foo@bar %  brew install jmespath/jmespath/jp
==> Tapping jmespath/jmespath
Cloning into '/usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath'...
remote: Enumerating objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Receiving objects: 100% (45/45), 9.70 KiB | 3.23 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb
jp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the jmespath/jmespath tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb:8

Error: Cannot tap jmespath/jmespath: invalid syntax in tap!
(py310) foo@bar % 
```

**Comment by dnishiyama** [comment]
I'm running into the same issue. Looks like the formula uses `bottle :unneeded` which used to be deprecated and is now disabled. 

https://stackoverflow.com/questions/45132704/what-does-bottle-unneeded-do

@lmeadors Where did you make those changes? Did you clone the repo and brew install from a local file?

**Comment by lmeadors** [comment]
I made the change in the file the error calls out:

/usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb

I got the other error after that - it included the command to run to update the OSX CLI dev tools.

After running that update command, re-running the brew install command worked for me.

**Comment by dnishiyama** [comment]
Thanks for the quick response. That was interesting because the error called out that same file to me, but it didn't exist. It looks like the install failure was rolling back the changes to the directory and deleting the cloned git repo. 

I ended up running `brew install jmespath/jmespath/jp -v` to get the git clone command and then ran that manually to get the repo to persist locally. 

Then I updated Command Line Tools and things are working now! Thanks

**Comment by rlvdx** [comment]
Doing this (to make the repo actually being stored on my filesystem):

```
I ended up running brew install jmespath/jmespath/jp -v to get the git clone command and then ran that manually to get the repo to persist locally.
```

Then commenting the line mentionned in the error, and finally (re)executing `brew install jmespath/jmespath/jp` worked for me too, thanks a lot :)

So, to sum up:
```shell
# Clone the repo because it's not being stored when the `brew install` fails
git clone https://github.com/jmespath/homebrew-jmespath /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath --origin=origin

# Comment or delete line 8 of /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb
# (because using `bottle :unneeded` is now deprecated and makes the installation fail)

# In my case, there was no need to update the Command line tools; they must've already been up to date.

# Install `jmespath`
brew install jmespath/jmespath/jp
```

**Comment by rebelnn** [comment]
I tried removing that `bottle :unneeded` line as rlvdx suggested but I'm still getting an error

```
Cloning into '/opt/homebrew/Library/Taps/jmespath/homebrew-jmespath'...
remote: Enumerating objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Receiving objects: 100% (45/45), 9.70 KiB | 9.70 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb
jp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the jmespath/jmespath tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb:8

Error: Cannot tap jmespath/jmespath: invalid syntax in tap!
```
Any idea?

**Comment by darkn3rd** [comment]
Any update on this? Stale project?

**Comment by donaldrich80** [comment]
brew might not work, but the executables are still being released

this worked for me today (you'll want to make sure to use the right package for your hardware)

```
curl -fLvo /usr/local/bin/jp https://github.com/jmespath/jp/releases/download/0.2.1/jp-darwin-arm64 && sudo chmod +x /usr/local/bin/jp 
```

**Comment by jamesls** [comment]
Fixed via https://github.com/jmespath/homebrew-jmespath/pull/1
