### ISSUE TITLE
jp for ARM7 cross-compiles and passes all tests under go 1.5 (Raspberry Pi 2)

### ISSUE THREAD

**Issue by vielmetti** [jmespath/jp#4]
I was able to get a running binary of jp for the Raspberry Pi by cross-compiling on my Mac and then scp'ing the binary over. The invocation on the Mac was

```
env GOOS=linux GOARCH=arm GOARM=7 go build -o jp.arm7
scp jp.arm7 emv@pi.local:src/jp/jp
```

The resulting binary passes all 9 tests in the test suite.

I cross-compiled in part because I wasn't able to get `jp` to build using the `go` provided when I did an `apt-get install golang` on the Pi 2; that reports out as `go version go1.0.2`. That build fails with this error:

```
/usr/lib/go/src/pkg/github.com/jmespath/jp/Godeps/_workspace/src/github.com/jmespath/go-jmespath/functions.go:771: syntax error: unexpected :, expecting ]
```

which I am guessing is a little syntax difference between go 1.0.2 and later versions of go.

**Comment by jamesls** [comment]
Awesome, thanks for looking into this.  I think I'll go ahead and include the .arm7 executables as part of the jp releases.
