### ISSUE TITLE
GPG key expired?

### ISSUE THREAD

**Issue by chriscroome** [jmespath/jp#41]
You might need to update your GPG key @jamesls ?

Import the key used to sign the binary package checksums:

```bash
gpg --keyserver hkps://keyserver.ubuntu.com --search-keys A0BE6CFACEC3BE69CAD146BBCD2646EDDCC1FDB6 
```

Download and check the checksums:

```bash
wget https://github.com/jmespath/jp/releases/download/0.2.1/jp-checksums.sha256.asc
gpg --verify jp-checksums.sha256.asc
gpg: Signature made Thu 30 Sep 2021 19:25:21 BST
gpg:                using RSA key A0BE6CFACEC3BE69CAD146BBCD2646EDDCC1FDB6
gpg: Good signature from "James Saryerwinnie <js@jamesls.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: A0BE 6CFA CEC3 BE69 CAD1  46BB CD26 46ED DCC1 FDB6
```

**Comment by springcomp** [comment]
@chriscroome  I would like to provide signed binaries [myself](https://github.com/jmespath-community/jp/releases/tag/v1.1.0).
However I have no idea where to start.
Would you be able to help me?

**Comment by chriscroome** [comment]
I've recently generated a new GPG key pair for myself using [this guide](https://github.com/drduh/YubiKey-Guide), do you have one, or ideally two YubiKeys? If you don't and you can afford it I'd suggest getting a pair of [YubiKey 5 Series](https://www.yubico.com/gb/store/#yubikey-5-series) keys and following this guide, it takes a few hours to work through but in the end you have a pair of keys that you simply need to insert, type a 6 digit pin for each time they are plugged in and then simply touch them to GPG sign / encrypt a file or git commit.

**Comment by jamesls** [comment]
Expiry of gpg key updated, should be good now.
