### ISSUE TITLE
Not Equal modifier not working

### ISSUE THREAD

**Issue by dsandros** [jmespath/jp#42]
Using the below query I get the expected results, but when replacing == with != it breaks and includes all SnapshotId's. Using \!= to fix parsing error.
Snapshots[?Tags[?Key=='Migration']].SnapshotId

I am able to get expression working correctly with the following but does seem like an extra step.
Snapshots[?!not_null(Tags[?Key == `Migration`].Value)].SnapshotId

**Comment by springcomp** [comment]
@dsandros  I cannot reproduce this issue.

Please, can you share which platform / OS and provide a sample input (and expected output document?)
