### ISSUE TITLE
Multihash does not work in jp v0.1.1

### ISSUE THREAD

**Issue by aronneagu** [jmespath/jp#5]
When performing the select `people[].{Name: name, State: state.name}` on

```
{
  "people": [
    {
      "name": "a",
      "state": {"name": "up"}
    },
    {
      "name": "b",
      "state": {"name": "down"}
    },
    {
      "name": "c",
      "state": {"name": "up"}
    }
  ]
}
```

It returns `SyntaxError: Incomplete expression.`
I am using jp-linux-amd64 v 0.1.1.
Running the same in jpterm version 0.2.1 the expression works and it returns

```
[
  {
    "State": "up", 
    "Name": "a"
  }, 
  {
    "State": "down", 
    "Name": "b"
  }, 
  {
    "State": "up", 
    "Name": "c"
  }
]
```

I am running Linux Ubuntu 14.04 (uname -a):
Linux aneagu 3.16.0-39-generic #53~14.04.1-Ubuntu SMP Wed May 27 10:03:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
How can I get the jp program to behave correctly, like jpterm? Thank you.

**Comment by jamesls** [comment]
I'm not able to repro the issue.  Could you show the exact commands you're running?  Here's what I tried:

```
$ cat /tmp/test.json
{
  "people": [
    {
      "name": "a",
      "state": {"name": "up"}
    },
    {
      "name": "b",
      "state": {"name": "down"}
    },
    {
      "name": "c",
      "state": {"name": "up"}
    }
  ]
}
$ jp --version
jp version 0.1.1
$ jp 'people[].{Name: name, State: state.name}' < /tmp/test.json
[
  {
    "Name": "a",
    "State": "up"
  },
  {
    "Name": "b",
    "State": "down"
  },
  {
    "Name": "c",
    "State": "up"
  }
]
```

**Comment by aronneagu** [comment]
James,
Thanks for the quick reply
I forgot to add the single quotes around the expression. I was using 
`jp people[].{Name: name, State: state.name} < /tmp/test.json`.
I was using the examples in the Readme.md and nowhere I saw the single quotes around the expression. 
As a side note,
`cat /tmp/test.json | jp 'people[].{Name: name, State: state.name}` works fine
`cat /tmp/test.json | jp people[].{Name: name, State: state.name}` 
returns 

```
SyntaxError: Incomplete expression
people[].{Name:
               ^
```

Now I understand. It breaks at the space, so that's why the quotes are necessary.
