### ISSUE TITLE
Example Usage is incorrect.

### ISSUE THREAD

**Issue by adilfulara** [jmespath/jp#7]
**Operating System: OSX El Capitan**
`➜  ~ uname -a`
`Darwin USHOLAFU1-ML 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`

`➜  ~ jp --version`
`jp version 0.1.1`

**Following works.**

`➜  ~ echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar`
`[
  "a",
  "b",
  "c"
]`

**Following does not work.**
`➜  ~ echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar[0]`
`Must provide at least one argument.`

**Comment by jamesls** [comment]
Interesting, I'm not seeing that behavior.  I'm also on OS X El Capitan:

```
$ echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar[0]
"a"
```

Could it be related to the shell you're using?  What happens if you quote the expression: `jp 'foo.bar[0]'`

**Comment by adilfulara** [comment]
If i drop down to bash, it works. so i think its zsh that is causing the problem. 
i have no idea what it could be though.
