### ISSUE TITLE
Error when expression end with a number

### ISSUE THREAD

**Issue by hoegertn** [jmespath/jp#8]
When I try do execute the following code it throws an error:

```
curl https://coreos.com/dist/aws/aws-stable.json -sS | jp "eu-central-1"

SyntaxError: Unexpected token at the end of the expresssion: tNumber
eu-central-1
  ^

```

Am I missing something obvious here?

EDIT: using latest version changed the error message

**Comment by jamesls** [comment]
A "key" in a document can either be quoted or unquoted.  In order to be unquoted it can only contain `[a-zA-Z0-9]` chars.  If contains anything else, it needs to surrounded with double quotes.  So for your example you'd need:

```
$ curl https://coreos.com/dist/aws/aws-stable.json -sS | jp '"eu-central-1"'
{
  "hvm": "ami-c90bf8a6",
  "pv": "ami-4704f728"
}
```

Let me know if you're still running into issues with this.

**Comment by hoegertn** [comment]
Thanks, it works.
